class OfficeOxideError(Exception): ...

class Document:
    @staticmethod
    def open(path: str) -> "Document": ...
    @staticmethod
    def from_bytes(data: bytes, format: str) -> "Document": ...
    def format_name(self) -> str: ...
    def plain_text(self) -> str: ...
    def to_markdown(self) -> str: ...
    def to_ir(self) -> dict: ...

def extract_text(path: str) -> str: ...
def to_markdown(path: str) -> str: ...
