"""Type stubs for the office_oxide native extension module.

These stubs cover the public API exposed by the Rust ``_native`` module.
Every `path` argument accepts ``str`` or any ``os.PathLike[str]``.
"""

from __future__ import annotations

from os import PathLike
from typing import Any, Literal, Optional, Type, Union

__version__: str

FormatName = Literal["docx", "xlsx", "pptx", "doc", "xls", "ppt"]
_Path = Union[str, PathLike[str]]
_CellValue = Union[None, str, bool, int, float]

class OfficeOxideError(Exception):
    """Raised for any parse, IO, or conversion failure inside office_oxide."""

class Document:
    """A parsed Office document (read-only).

    Supports use as a context manager::

        with Document.open("report.docx") as doc:
            print(doc.plain_text())
    """

    @staticmethod
    def open(path: _Path, /) -> "Document": ...
    @staticmethod
    def from_bytes(data: bytes, format: FormatName, /) -> "Document": ...
    @property
    def format(self) -> FormatName: ...
    def format_name(self) -> FormatName: ...
    def plain_text(self) -> str: ...
    def to_markdown(self) -> str: ...
    def to_html(self) -> str: ...
    def to_ir(self) -> dict[str, Any]: ...
    def save_as(self, path: _Path, /) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Document": ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[Any],
    ) -> bool: ...

class EditableDocument:
    """An editable Office document (DOCX, XLSX, PPTX)."""

    @staticmethod
    def open(path: _Path, /) -> "EditableDocument": ...
    def replace_text(self, find: str, replace: str, /) -> int: ...
    def set_cell(
        self, sheet_index: int, cell_ref: str, value: _CellValue, /
    ) -> None: ...
    def save(self, path: _Path, /) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "EditableDocument": ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[Any],
    ) -> bool: ...

def extract_text(path: _Path, /) -> str: ...
def to_markdown(path: _Path, /) -> str: ...
def to_html(path: _Path, /) -> str: ...
def version() -> str: ...
